
import { GoogleGenAI, Type } from "@google/genai";
import { FaceAnalysis } from "../types";

const getAIClient = () => {
  return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
};

export const analyzeFace = async (base64Image: string): Promise<FaceAnalysis> => {
  const ai = getAIClient();
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: [
      {
        parts: [
          { inlineData: { mimeType: 'image/jpeg', data: base64Image } },
          { text: "Analyze this person's face for hairstyle recommendations. Identify their face shape, jawline structure, and hair density. Provide a list of recommended hairstyle types." }
        ]
      }
    ],
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          faceShape: { type: Type.STRING },
          jawline: { type: Type.STRING },
          hairDensity: { type: Type.STRING },
          recommendations: {
            type: Type.ARRAY,
            items: { type: Type.STRING }
          }
        },
        required: ["faceShape", "jawline", "hairDensity", "recommendations"]
      }
    }
  });

  try {
    return JSON.parse(response.text || '{}') as FaceAnalysis;
  } catch (e) {
    console.error("Failed to parse face analysis", e);
    return {
      faceShape: "Oval",
      jawline: "Balanced",
      hairDensity: "Medium",
      recommendations: ["Classic", "Modern", "Fade"]
    };
  }
};

export const transformHairstyle = async (base64Image: string, stylePrompt: string, colorPrompt: string): Promise<string> => {
  const ai = getAIClient();
  
  // Using gemini-2.5-flash-image for image editing/generation
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { mimeType: 'image/jpeg', data: base64Image } },
        { text: `Modify this photo. Keep the face, expression, lighting, and background exactly the same. Replace ONLY the hair with a ${colorPrompt} colored ${stylePrompt}. The new hair must blend realistically with the natural hairline and skin. High fidelity, cinematic lighting, 4k quality.` }
      ]
    }
  });

  let transformedUrl = '';
  if (response.candidates?.[0]?.content?.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        transformedUrl = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }
  }

  if (!transformedUrl) {
    throw new Error("No image generated by Gemini");
  }

  return transformedUrl;
};
